class TestGramatica{
    
ValidarPaginaInicio(){
    let tiempo=1500
    cy.get(':nth-child(1) > .text-dark').should('have.text','Inicio')
    cy.wait(tiempo)
    cy.get(':nth-child(2) > .text-dark').should('have.text','Materias primas')
    cy.wait(tiempo)
    cy.get(':nth-child(3) > .text-dark').should('have.text','Solicitudes')
    cy.wait(tiempo)
    cy.get(':nth-child(4) > .btn').should('have.text','Cerrar sesión')
    cy.wait(tiempo)
    cy.get('.navbar-brand').should('have.text','FactoryApp')
    cy.wait(tiempo)
    cy.get('h1').should('contain.text','Hola,')
    cy.wait(tiempo)
    cy.get('h1').should('contain.text','. ¡Aprendamos juntos!')
    cy.wait(tiempo)
    cy.get('p').should('have.text','En este proyecto exploramos cómo integrar Elsa a una aplicación.')
    cy.wait(tiempo)
    cy.get('h4').should('have.text','Variables de ambiente:')
    cy.wait(tiempo)
    cy.get(':nth-child(2) > div > ul > :nth-child(1)').should('have.text','ELSA_SERVER http://localhost:8011')
    cy.wait(tiempo)
    cy.get(':nth-child(2) > div > ul > :nth-child(2)').should('have.text','API_SERVER http://localhost:8010')
    cy.wait(tiempo)
    //cy.get('').should('have.text','')
}
ValidarMateriaPrima(){
    let tiempo=1500
    cy.get(':nth-child(2) > .text-dark').should('be.visible').click()
    cy.wait(tiempo)
    cy.get('h2').should('have.text','Materias primas')
    cy.wait(tiempo)
    cy.get('p').should('have.text','A continuación podrá observar la cantidad de materia prima que se encuentra en bodega de la fábrica. Visita la opción del menú Solicitudes para conocer el estado de tus solicitudes o crear una nueva.')
    cy.wait(tiempo)
    cy.get('thead > tr > :nth-child(1)').should('have.text','Nombre')
    cy.wait(tiempo)
    cy.get('thead > tr > :nth-child(2)').should('have.text','Cantidad Disponible')
    cy.wait(tiempo)
    cy.get('tbody > :nth-child(1) > :nth-child(1)').should('have.text','Carbón x2 kg.')
    cy.wait(tiempo)
    cy.get('tbody > :nth-child(2) > :nth-child(1)').should('have.text','Cemento x10 kg.')
    cy.wait(tiempo)
    cy.get('tbody > :nth-child(3) > :nth-child(1)').should('have.text','Hierro x5 kg.')
    cy.wait(tiempo)
    cy.get('tbody > :nth-child(4) > :nth-child(1)').should('have.text','Petróleo x5 gal.')
    cy.wait(tiempo)

}
ValidarSolicitudes(){
    let tiempo =1500
    cy.get(':nth-child(3) > .text-dark').should('be.visible').click()
    cy.wait(tiempo)
    cy.get('h2').should('have.text','Solicitudes')
    cy.wait(tiempo)
    cy.get('p').should('have.text',"A continuación podrá observar el estado de las diferentes solicitudes en las que usted se encuentre relacionado. Para crear una nueva solicitud, haga click en el botón 'Nueva solicitud'.")
    cy.wait(tiempo)
    cy.get('.btn-info').should('have.text','Nueva solicitud')
    cy.wait(tiempo)
    cy.get('thead > tr > :nth-child(1)').should('have.text','Id')
    cy.wait(tiempo)
    cy.get('thead > tr > :nth-child(2)').should('have.text','Creada por')
    cy.wait(tiempo)
    cy.get('thead > tr > :nth-child(3)').should('have.text','Aprovador')
    cy.wait(tiempo)
    cy.get('thead > tr > :nth-child(4)').should('have.text','Fecha de Creación')
    cy.wait(tiempo)
    cy.get('thead > tr > :nth-child(5)').should('have.text','Estado')
    cy.wait(tiempo)
    cy.get('thead > tr > :nth-child(6)').should('have.text','Total de Elementos')
}
ValidarNuevaSolicitud(){
    let tiempo=1500
    cy.get(':nth-child(3) > .text-dark').should('be.visible').click()
    cy.wait(tiempo)
    cy.get('.btn-info').should('be.visible').click()
    cy.wait(tiempo)
    cy.get('h2').should('have.text','Crear nueva solicitud')
    cy.wait(tiempo)
    cy.get('p').should('have.text',"Seleccione la materia prima que desea solicitar junto con la cantidad necesaria y haga click en el botón 'Agregar' para agregarlo a los detalles. Una vez finalizado, guarde la solicitud haciendo click en el botón 'Guardar solicitud' para dejarla en estado de borrador.")
    cy.wait(tiempo)
    cy.get(':nth-child(1) > .input-group-text').should('have.text','Materia prima')
    cy.wait(tiempo)
    cy.get('.form-control').should('have.text','Seleccione la materia primaCarbón x2 kg.Cemento x10 kg.Hierro x5 kg.Petróleo x5 gal.')
    cy.wait(tiempo)
    cy.get(':nth-child(3) > .input-group-text').should('have.text','Cantidad')
    cy.wait(tiempo)
    cy.get('input').should('have.attr','min').and('include','0')
    cy.wait(tiempo)
    cy.get('input').should('have.value','0').should('have.attr','type').should('include','number')
    cy.wait(tiempo)
    cy.get('.input-group-append > .btn').should('have.text','Agregar')
    cy.wait(tiempo)
    cy.get('thead > tr > :nth-child(1)').should('have.text','Nombre')
    cy.wait(tiempo)
    cy.get('tr > :nth-child(2)').should('have.text','Cantidad a solicitar')
    cy.wait(tiempo)
    cy.get('td').should('have.text','Sin registros')
    cy.wait(tiempo)
    cy.get('.btn-primary').should('have.text','Guardar solicitud')
}
PaginaPrincipal(){
cy.get('.text-center').should("have.text','Por favor escoja un usuario de la siguiente lista y presione en el botón 'Empezar sesión' para simular la sesión")
cy.get('.form-control').should('have.text','Seleccione un usuario')
//cy.get('').should('have.text','')

}
}//Final
export default TestGramatica;